# Generated by Django 3.2.9 on 2021-11-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211113_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhostaccounts',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='venueholderaccounts',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
