# Generated by Django 3.2.9 on 2021-11-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_eventcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_address', models.TextField()),
                ('venue_description', models.TextField()),
                ('venue_cost', models.IntegerField()),
                ('venue_capacity', models.IntegerField()),
                ('venue_seating_type', models.CharField(max_length=50)),
                ('venue_special_features', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventcategories')),
                ('venue_holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venueholderaccounts')),
            ],
        ),
    ]
