# Generated by Django 3.2.9 on 2021-12-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='venue_image',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
