# Generated by Django 3.2.9 on 2021-12-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_venues_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.IntegerField()),
                ('event_month', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('event_attendees', models.IntegerField()),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventhostaccounts')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venues')),
            ],
        ),
    ]
